server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_security?characterEncoding=UTF-8
    username: root
    password: admin123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jgdabc.entity
