server:
  port: 8080
spring:
  application:
    name: auth_jwt
  datasource:
    url: jdbc:mysql://localhost:3306/auth_jwt?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.jgdabc.entity
  mapper-locations: classpath:/mapper/*xml
